version: '3.7'
services:
  app:
    build:
      context: .
    image: gradle:8-jdk17
    container_name: ontology
    depends_on:
      - es
    ports:
      - "8080:8080" # application
      - "7777:7777" # debugger
    volumes:
      - ./:/opt/target:ro
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
    ports:
      - "9200:9200"
    container_name: elastic
    volumes:
      - ./data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
