version: '3.7'
services:
  app:
    build:
      context: .
    image: gradle:8-jdk17
    container_name: ontology
    depends_on:
      - es
    ports:
      - "7777:7777" # debugger
    volumes:
      - ./src/main/resources/application.yml:/home/ontology/resources/application.yml:ro
      - ./src/main/resources/ontologies:/home/ontology/src/main/resources/ontologies:ro
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
    ports:
      - "9200:9200"
    container_name: elastic
    volumes:
      - ./data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
