micronaut:
  application:
    name: ontology
    version: 0.1

elasticSearch:
  servers:
    - localhost
  indexName: ontology-local

ontologyFiles:
  files:
    -
      name: doid.owl
      type: disease
      prefix:
      fileType: OWL
    -
      name: data-use.owl
      type: organization
      prefix:
      fileType: OWL
